name: On push workflow
on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
jobs:
  build:
    name: Run on push
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.event_name }}
