name: On tag workflow
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Run on tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run common steps first
        id: common-steps
        uses: ./.github/actions/common-steps
        with:
          wf_ref: ${{ github.ref }}
          wf_event_name: ${{ github.event_name }}
      - name: Step on tag workflow
        run: echo "I am tag workflow"
