name: On tag workflow
on:
  push:
    branches-ignore:
      - "*"
    tags:
      - "v*"
jobs:
  build:
    name: Run on tag
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.event_name }}
